name: binding_helper
description: A easy way to use WidgetsBinding
version: 0.0.2
author: JZoom <jzoom8112@gmail.com>
homepage: https://github.com/best-flutter/binding_helper


environment:
  sdk: ">=2.0.0-dev.48.0 <3.0.0"
  flutter: ">=0.1.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: